name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 1

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip \
            openjdk-17-jdk \
            libffi-dev libssl-dev \
            libbz2-dev libncurses5-dev libsqlite3-dev zlib1g-dev libjpeg-dev

      - name: Create & activate venv, install Buildozer & SDK tools, build APK
        shell: bash -l {0}
        env:
          ANDROIDSDK: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
          ANDROIDNDK: ${{ github.workspace }}/.buildozer/android/platform/android-ndk-r25b
        run: |
          # create & enter venv
          python3 -m venv .venv
          sed -i 's/\r$//' .venv/bin/activate
          source .venv/bin/activate

          # install Buildozer + friends
          pip install --upgrade pip setuptools wheel Cython buildozer

          # accept all Android SDK licenses
          yes | "$ANDROIDSDK/tools/bin/sdkmanager" --sdk_root="$ANDROIDSDK" --licenses

          # install exactly what your spec needs
          yes | "$ANDROIDSDK/tools/bin/sdkmanager" --sdk_root="$ANDROIDSDK" \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;34.0.0"

          # kick off the Buildozer build
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
