name: Build Android APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv git zip unzip libffi-dev \
             libssl-dev libbz2-dev libncurses5-dev libsqlite3-dev zlib1g-dev libjpeg-dev
      - run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip setuptools wheel Cython buildozer
      - env:
          ANDROIDSDK: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
          ANDROIDNDK: ${{ github.workspace }}/.buildozer/android/platform/android-ndk-r25b
        run: |
          . .venv/bin/activate
          buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: celtic-handpan-apk
          path: bin/*.apk
